version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.14
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - run: go mod download
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run: go test -count=1 ./...
      - slack/status:
          fail_only: false
          webhook: '${SLACK_WEBHOOK}'
  deploy:
    docker:
      - image: circleci/golang:1.14
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - run: go mod download
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run: make
      - aws-cli/setup
      - serverless/setup:
          app-name: gitwize
          org-name: wizeline
      - run:
          command: serverless deploy -v
          name: deploy
      - slack/status:
          fail_only: false
          webhook: '${SLACK_WEBHOOK}'
orbs:
  slack: circleci/slack@3.4.2
  aws-cli: circleci/aws-cli@1.0.0
  node: circleci/node@3.0.0
  serverless: circleci/serverless-framework@1.0.1
workflows:
  cicd-workflow:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - /deploy-.*/
